### PR TITLE
Install required system packages for gaia node modules to build as expec...

### PR DESCRIPTION
**Pull request by nullaus**
...ted. r=jlal

### CODE REVIEW

**Comment by lightsofapollo-taskcluster** [comment]
@nullaus lgtm

**Comment by nullaus** [comment]
Cool. Merging. Passes muster under development as well.

**Comment by nullaus** [comment]
Looks like you'll have to merge this or add me to the taskcluster org :)

**Comment by nullaus** [comment]
published new docker image to taskcluster/npm-cache:0.1.0

**Pull request merged**
